# ==============================================================================
# PowerFlow — Git Release Workflow
# ==============================================================================
# Domain   : Git
# File     : components/git/release.ps1
# Purpose  : Interactive semver bump → settings update → commit → tag → push
#            workflow. Reads the current version from config/PowerFlow.settings.ps1
#            (falls back to latest git tag), lets you pick patch/minor/major/custom
#            via fzf, updates the settings file automatically, then commits,
#            pushes, tags, and pushes the tag — triggering the CI release pipeline.
# Functions: git-release, git-rl, Show-GitReleaseSetupPrompt
# Depends  : config/PowerFlow.settings.ps1
#            Copy-ToClipboard (platform/<os>/adapters/clipboard.ps1)
# ==============================================================================

# `git-rl -h` — print the AI setup prompt for a NEW project.
#
# git-rl only works in a repo that satisfies its contract (a version source, a parseable
# CHANGELOG, and a tag-triggered pipeline). This prints a self-contained prompt to paste
# into an AI assistant open in that repo, which will build the whole setup.
#
# The doc is resolved from the PowerFlow INSTALL root, not the current directory — you run
# this from inside the project you are setting up, which knows nothing about PowerFlow.
# Locate the setup docs.
#
# These ship with PowerFlow, so `install.ps1` MUST copy docs/git-rl/ — it previously only
# copied config/, components/, platform/ and windows-only/, which meant `git-rl -h` found
# nothing after a real install. If they are still missing (an older install), fall back to
# fetching them from GitHub so help never simply breaks.
function Get-GitReleaseDocs {
    $promptDoc = Join-Path $script:PowerFlowRoot 'docs/git-rl/SETUP-PROMPT.md'
    $manualDoc = Join-Path $script:PowerFlowRoot 'docs/git-rl/README.md'

    $rawPrompt = $null
    $rawManual = $null

    if (Test-Path $promptDoc) { $rawPrompt = Get-Content $promptDoc -Raw }
    if (Test-Path $manualDoc) { $rawManual = Get-Content $manualDoc -Raw }

    if (-not $rawPrompt) {
        Write-Host "ℹ️  Setup docs not found locally — fetching them..." -ForegroundColor DarkGray
        $base = "https://raw.githubusercontent.com/$script:POWERFLOW_REPO/main/docs/git-rl"
        try {
            $rawPrompt = (Invoke-WebRequest -Uri "$base/SETUP-PROMPT.md" -UseBasicParsing -TimeoutSec 15).Content
            $rawManual = (Invoke-WebRequest -Uri "$base/README.md"       -UseBasicParsing -TimeoutSec 15).Content
        } catch {
            Write-Host "❌ Could not load the setup docs (offline?)." -ForegroundColor Red
            Write-Host "   https://github.com/$script:POWERFLOW_REPO/blob/main/docs/git-rl/SETUP-PROMPT.md" -ForegroundColor Cyan
            return $null
        }
    }

    # The doc wraps the prompt in a ```text fence so it renders on GitHub. Extract the
    # body — the user pastes the PROMPT, not the documentation around it.
    $prompt = if ($rawPrompt -match '(?s)```text\r?\n(.*?)\r?\n```') { $matches[1] } else { $rawPrompt }

    return [pscustomobject]@{
        Prompt = $prompt
        Manual = $rawManual
    }
}

# Write the self-contained guide into a project. Separated from the prompt flow so it can
# be called (and tested) directly.
function Write-GitReleaseGuide {
    param([Parameter(Mandatory)][string]$ProjectRoot)

    $docs = Get-GitReleaseDocs
    if (-not $docs) { return $false }

    $docsDir = Join-Path $ProjectRoot 'docs'
    if (-not (Test-Path $docsDir)) {
        New-Item -ItemType Directory -Path $docsDir -Force | Out-Null
        Write-Host "📂 Created: docs/" -ForegroundColor Green
    }

    $target = Join-Path $docsDir 'git-release-help.md'
    if (Test-Path $target) {
        Write-Host "⚠️  docs/git-release-help.md already exists." -ForegroundColor Yellow
        if ((Read-Host "Overwrite it? (y/n)") -ne 'y') {
            Write-Host "❌ Cancelled — nothing was written." -ForegroundColor Yellow
            return $false
        }
    }

    # One self-contained document: the AI prompt AND the manual, so the project keeps
    # everything even if PowerFlow is never installed on this machine again.
    $content = @"
# Releasing this project with ``git-rl``

> Generated by ``git-rl -h`` on $(Get-Date -Format 'yyyy-MM-dd').
> Source: https://github.com/$script:POWERFLOW_REPO

This document contains two things:

1. **The AI setup prompt** — paste it into an AI assistant open in this repository and it
   will build the entire release pipeline.
2. **The manual** — what that setup *is*, and how to cut a release by hand if the tooling
   is ever unavailable.

---

## 1. AI setup prompt

Copy everything inside the block below and paste it into your AI coding assistant.

``````text
$($docs.Prompt)
``````

---

## 2. The manual

$($docs.Manual)
"@

    Set-Content -Path $target -Value $content -Encoding UTF8
    Write-Host "✅ Wrote: docs/git-release-help.md" -ForegroundColor Green
    Write-Host "   $target" -ForegroundColor DarkGray

    try {
        Copy-ToClipboard $docs.Prompt
        Write-Host "📋 The AI prompt is on your clipboard — paste it into your assistant now." -ForegroundColor Green
    } catch {
        Write-Host "💡 Open docs/git-release-help.md and copy the prompt from section 1." -ForegroundColor DarkGray
    }

    return $true
}

function Show-GitReleaseSetupPrompt {

    $cwd = (Get-Location).Path

    Write-Host ""
    Write-Host "╭─ 🚀 git-rl — SET UP A NEW PROJECT ──────────────────────────────────────────╮" -ForegroundColor Cyan
    Write-Host "│  git-rl only works in a repo that has:                                       │" -ForegroundColor Cyan
    Write-Host "│    1. a version source   2. a parseable CHANGELOG   3. a v* tag pipeline     │" -ForegroundColor Cyan
    Write-Host "│                                                                             │" -ForegroundColor Cyan
    Write-Host "│  This writes the full setup guide INTO your project, and copies the AI       │" -ForegroundColor Cyan
    Write-Host "│  prompt to your clipboard.                                                   │" -ForegroundColor Cyan
    Write-Host "╰─────────────────────────────────────────────────────────────────────────────╯" -ForegroundColor Cyan
    Write-Host ""

    # ── The only question that matters: are you in the right folder? ──────────
    # Nothing is printed to the terminal unless the answer is yes — dumping a 13k-char
    # prompt into the scrollback when the user is in the wrong directory is useless.
    $choices = @(
        "yes`t✅ Yes — I'm in my project folder. Write the guide here."
        "no`t↩️  No — I'll navigate to my project first."
    )

    $answer = $null
    if (Get-Command fzf -ErrorAction SilentlyContinue) {
        $selection = $choices | fzf --ansi --reverse --height=25% --border --no-sort `
            --delimiter="`t" --with-nth=2.. `
            --prompt="Are you in your project folder? " `
            --header="📁 $cwd"
        if ($selection) { $answer = ($selection -split "`t", 2)[0].Trim() }
    }
    else {
        Write-Host "📁 Current folder: $cwd" -ForegroundColor White
        Write-Host ""
        $answer = if ((Read-Host "Are you in your project folder? (y/n)") -match '^y') { 'yes' } else { 'no' }
    }

    # ── Not in the project: say so, and get out of the way ────────────────────
    if ($answer -ne 'yes') {
        Write-Host ""
        Write-Host "📂 Navigate to your project, then run " -NoNewline -ForegroundColor Yellow
        Write-Host "git-rl -h" -NoNewline -ForegroundColor Cyan
        Write-Host " again." -ForegroundColor Yellow
        Write-Host "   e.g.  " -NoNewline -ForegroundColor DarkGray
        Write-Host "nav my-project" -NoNewline -ForegroundColor Cyan
        Write-Host "   or   " -NoNewline -ForegroundColor DarkGray
        Write-Host "cd path\to\project" -ForegroundColor Cyan
        Write-Host ""
        return
    }

    # ── Yes: write the guide ──────────────────────────────────────────────────
    Write-Host "📁 Target project: $cwd" -ForegroundColor Cyan

    if (-not (git rev-parse --git-dir 2>$null)) {
        Write-Host "⚠️  This folder is not a git repository — git-rl will need one." -ForegroundColor Yellow
        if ((Read-Host "Write the guide here anyway? (y/n)") -ne 'y') {
            Write-Host "❌ Cancelled." -ForegroundColor Yellow
            return
        }
    }

    if (-not (Write-GitReleaseGuide -ProjectRoot $cwd)) { return }

    Write-Host ""
    Write-Host "Next:" -ForegroundColor Cyan
    Write-Host "  1. Paste the prompt into your AI assistant (it is on your clipboard)." -ForegroundColor White
    Write-Host "  2. Let it create the version file, CHANGELOG and .github/workflows/." -ForegroundColor White
    Write-Host "  3. Run " -NoNewline -ForegroundColor White
    Write-Host "git-rl" -NoNewline -ForegroundColor Yellow
    Write-Host " to cut your first release." -ForegroundColor White
    Write-Host ""
}

function git-release {
    [CmdletBinding()]
    param(
        [Alias('h', 'help', '?')]
        [switch]$ShowSetupPrompt
    )

    # ── -h / -help: print the setup prompt and stop ───────────────────────────
    if ($ShowSetupPrompt) {
        Show-GitReleaseSetupPrompt
        return
    }

    # ── Guard: must be in a git repo ─────────────────────────────────────────
    if (-not (git rev-parse --git-dir 2>$null)) {
        Write-Host "❌ Not in a Git repository" -ForegroundColor Red
        return
    }

    $branch   = git rev-parse --abbrev-ref HEAD 2>$null
    $repoRoot = git rev-parse --show-toplevel 2>$null

    # ── Resolve current version ───────────────────────────────────────────────
    # Reads the project's NATIVE version file — package.json, pyproject.toml,
    # Cargo.toml, *.csproj, build.gradle, VERSION, or PowerFlow's settings file —
    # and falls back to the latest git tag. See components/git/version-files.ps1.
    $resolved       = Get-ProjectVersion -RepoRoot $repoRoot
    $currentVersion = $resolved.Version
    $versionSources = @($resolved.Sources)
    $versionSource  = $resolved.From

    if ($versionSource -eq 'default') {
        Write-Host "⚠️  No version file or tag found — starting from v0.0.0" -ForegroundColor Yellow
    }

    # ── Version drift: several version files that disagree ────────────────────
    # e.g. package.json says 1.2.0 while VERSION says 1.1.0. Bumping from an
    # arbitrary one of them silently entrenches the mistake, so stop and ask.
    if (Test-VersionDrift -Sources $versionSources) {
        Write-Host ""
        Write-Host "⚠️  VERSION DRIFT — these files disagree:" -ForegroundColor Yellow
        foreach ($s in $versionSources) {
            Write-Host ("     {0,-32} {1}" -f $s.Label, $s.Version) -ForegroundColor White
        }
        Write-Host ""
        Write-Host "   Bumping will set ALL of them to the same new version," -ForegroundColor DarkGray
        Write-Host "   computed from '$currentVersion' ($($versionSources[0].Label))." -ForegroundColor DarkGray
        Write-Host ""
        if ((Read-Host "Continue and bring them into sync? (y/n)") -ne 'y') {
            Write-Host "❌ Cancelled — fix the versions by hand, then re-run." -ForegroundColor Yellow
            return
        }
    }

    # ── Parse version parts ───────────────────────────────────────────────────
    if ($currentVersion -notmatch '^(\d+)\.(\d+)\.(\d+)') {
        Write-Host "❌ Cannot parse version '$currentVersion' — expected X.Y.Z" -ForegroundColor Red
        return
    }
    $maj = [int]$matches[1]
    $min = [int]$matches[2]
    $pat = [int]$matches[3]

    $candidates = @{
        patch  = "$maj.$min.$($pat + 1)"
        minor  = "$maj.$($min + 1).0"
        major  = "$($maj + 1).0.0"
    }

    # ── Stage 1: fzf bump-type selector ──────────────────────────────────────
    $sourceLabel = if ($versionSource -eq 'files') { ($versionSources.Label -join ' + ') }
                   elseif ($versionSource -eq 'tag') { 'latest git tag (no version file)' }
                   else { 'default (no version found)' }

    $choices = @(
        "patch    v$currentVersion  →  v$($candidates.patch)    bug fixes, dependency updates",
        "minor    v$currentVersion  →  v$($candidates.minor)    new features, non-breaking changes",
        "major    v$currentVersion  →  v$($candidates.major)    breaking changes",
        "custom   enter a specific version number"
    )

    $selected = $choices | fzf `
        --ansi `
        --no-multi `
        --reverse `
        --border=rounded `
        --height=35% `
        --prompt="  Bump type: " `
        --header="🚀 Release Workflow   Current: v$currentVersion ($sourceLabel)   Branch: $branch" `
        --header-first `
        --color="header:bold:magenta,prompt:bold:cyan,border:magenta,pointer:yellow,hl:green" `
        --margin=1 `
        --padding=1

    if (-not $selected) {
        Write-Host "❌ Release cancelled" -ForegroundColor Yellow
        return
    }

    # ── Resolve new version ───────────────────────────────────────────────────
    $newVersion = switch -Regex ($selected) {
        '^patch'  { $candidates.patch }
        '^minor'  { $candidates.minor }
        '^major'  { $candidates.major }
        '^custom' {
            $input = Read-Host "📦 Version (X.Y.Z, without the v)"
            if ($input -notmatch '^\d+\.\d+\.\d+$') {
                Write-Host "❌ Invalid format — use semantic versioning: X.Y.Z" -ForegroundColor Red
                return
            }
            $input
        }
    }

    $newTag = "v$newVersion"

    # ── Guard: tag must not already exist ─────────────────────────────────────
    if (git tag -l $newTag 2>$null) {
        Write-Host "❌ Tag $newTag already exists locally" -ForegroundColor Red
        Write-Host "💡 Run: git tag -d $newTag   to remove it first" -ForegroundColor DarkGray
        return
    }

    # ── Stage 2: fzf release description ─────────────────────────────────────
    $status = git status --short
    $fileLines = if ($status) {
        @($status) | ForEach-Object {
            $code = $_.Substring(0, 2).Trim()
            $file = $_.Substring(3)
            switch ($code) {
                "M"  { "   📝 $file (modified)" }
                "A"  { "   ➕ $file (added)" }
                "D"  { "   🗑  $file (deleted)" }
                "R"  { "   🔄 $file (renamed)" }
                "??" { "   ❓ $file (untracked)" }
                default { "   📄 $file ($code)" }
            }
        }
    } else { @("   (no uncommitted changes — tagging HEAD)") }

    $recentCommits = git log --oneline --color=always -n 5 2>$null
    $commitLines = if ($recentCommits) {
        $arr = @($recentCommits)
        for ($i = 0; $i -lt $arr.Count; $i++) { "   $($i+1). $($arr[$i])" }
    } else { @("   (no commits yet)") }

    # Show EVERY version file that will be rewritten, not just PowerFlow's.
    $settingsNote = if ($versionSources.Count -gt 0) {
        @($versionSources | ForEach-Object { "   📄 $($_.Label) → $newVersion" })
    } else {
        @("   ℹ️  No version file — the tag alone carries the version")
    }

    $formLines = @(
        "",
        "   🏷️  Tag      :  $newTag",
        "   📦 Version  :  v$currentVersion  →  v$newVersion",
        "   🌿 Branch   :  $branch",
        ""
    ) + $settingsNote + @(
        "",
        "   📋 Files to commit:"
    ) + $fileLines + @(
        "",
        "   📚 Recent commits:"
    ) + $commitLines + @(
        "",
        "   💬 Type your release description above and press Enter"
    )

    $fzfOut = $formLines | fzf `
        --ansi `
        --reverse `
        --border=rounded `
        --height=85% `
        --prompt="  Description: " `
        --header="🚀 Release $newTag — Commit → Push → Tag → Push Tag" `
        --header-first `
        --color="header:bold:magenta,prompt:bold:green,border:magenta,spinner:yellow" `
        --margin=1 `
        --padding=1 `
        --print-query `
        --expect=enter

    $description = if ($fzfOut) { @($fzfOut)[0].Trim() } else { "" }

    if ([string]::IsNullOrWhiteSpace($description) -or $description.Length -lt 3) {
        Write-Host "❌ Description too short — release cancelled" -ForegroundColor Yellow
        return
    }

    $commitMsg = "vr-commit ($newTag) - $description"

    # ── Update EVERY version file ─────────────────────────────────────────────
    # All of them, together — that is what stops package.json and VERSION drifting
    # apart. Formatting is preserved (regex rewrite, never a JSON reserialise).
    if ($versionSources.Count -gt 0) {
        Write-Host "📄 Updating version file(s) to $newVersion..." -ForegroundColor Yellow

        $written = @(Update-ProjectVersion -Sources $versionSources -NewVersion $newVersion)

        if ($written.Count -ne $versionSources.Count) {
            Write-Host ""
            Write-Host "❌ Not every version file could be updated — release cancelled." -ForegroundColor Red
            Write-Host "   Nothing has been committed, tagged or pushed." -ForegroundColor DarkGray
            Write-Host "💡 Fix the file(s) above, then re-run git-rl." -ForegroundColor DarkGray
            return
        }
    }
    else {
        Write-Host "ℹ️  No version file — the tag will carry the version." -ForegroundColor DarkGray
    }

    # ── git add ───────────────────────────────────────────────────────────────
    Write-Host "📂 Staging changes..." -ForegroundColor Yellow
    git add .
    if ($LASTEXITCODE -ne 0) { Write-Host "❌ git add failed" -ForegroundColor Red; return }
    Write-Host "✅ Files staged" -ForegroundColor Green

    # ── git commit ────────────────────────────────────────────────────────────
    Write-Host "💾 Committing..." -ForegroundColor Yellow
    Write-Host "   $commitMsg" -ForegroundColor DarkGray
    git commit -m $commitMsg
    if ($LASTEXITCODE -ne 0) { Write-Host "❌ git commit failed" -ForegroundColor Red; return }
    Write-Host "✅ Commit created" -ForegroundColor Green

    # ── git push (commit) ─────────────────────────────────────────────────────
    Write-Host "🚀 Pushing commit..." -ForegroundColor Yellow
    $hasUpstream = git rev-parse --abbrev-ref --symbolic-full-name "@{u}" 2>$null
    if ($hasUpstream) { git push } else { git push -u origin $branch }
    if ($LASTEXITCODE -ne 0) { Write-Host "❌ git push failed" -ForegroundColor Red; return }
    Write-Host "✅ Commit pushed to $branch" -ForegroundColor Green

    # ── git tag ───────────────────────────────────────────────────────────────
    Write-Host "🏷️  Creating tag $newTag..." -ForegroundColor Cyan
    git tag $newTag
    if ($LASTEXITCODE -ne 0) {
        Write-Host "❌ git tag failed" -ForegroundColor Red
        Write-Host "💡 Run: git tag -d $newTag   then try again" -ForegroundColor DarkGray
        return
    }
    Write-Host "✅ Tag $newTag created" -ForegroundColor Green

    # ── git push tag ──────────────────────────────────────────────────────────
    Write-Host "🚀 Pushing tag $newTag..." -ForegroundColor Cyan
    git push origin $newTag
    if ($LASTEXITCODE -ne 0) {
        Write-Host "❌ Failed to push tag" -ForegroundColor Red
        Write-Host "💡 Run manually: git push origin $newTag" -ForegroundColor DarkGray
        return
    }

    # ── Success ───────────────────────────────────────────────────────────────
    $remoteUrl = git remote get-url origin 2>$null
    $releaseUrl = if ($remoteUrl -match 'github\.com[:/](.+?)(?:\.git)?$') {
        "https://github.com/$($matches[1])/releases/tag/$newTag"
    } else { $null }

    Write-Host ""
    Write-Host "🎉 Release $newTag is live!" -ForegroundColor Magenta
    Write-Host "🔄 GitHub Actions release pipeline triggered" -ForegroundColor Cyan
    if ($releaseUrl) {
        Write-Host "📦 $releaseUrl" -ForegroundColor DarkCyan
    }
    Write-Host ""
}

function git-rl { git-release @args }

# ── pwsh-h registration ───────────────────────────────────────────────────────
Register-PFCommand -Name 'git-rl' -Aliases @('git-release') -Section '🎯 ENHANCED GIT WORKFLOW' -Synopsis 'release: bump version, commit, tag, push - any project' -Example 'git-rl · git-rl -h (set up a project)'
