# ==============================================================================
# PowerFlow — Environment Adapter (Linux)
# ==============================================================================
# Domain   : Platform / Linux
# File     : platform/linux/adapters/env.ps1
# Purpose  : Read and write a persistent PATH
# Contract : Get-PersistentPath, Add-PersistentPathEntry, Test-PersistentPathEntry,
#            Get-PathScopeLabel, Get-PathFragmentPath
# Depends  : Assert-Admin (platform/linux/adapters/elevation.ps1),
#            Get-PowerFlowConfigPath (platform/linux/adapters/locations.ps1)
# ==============================================================================
#
# Linux has no registry. A "persistent PATH" is just a line in a startup file.
# PowerFlow owns exactly one file so it can add and remove entries cleanly without
# ever rewriting a file the user owns:
#
#   User   -> ~/.config/powerflow/path.ps1   (sourced by the PowerFlow profile)
#   System -> /etc/profile.d/powerflow-path.sh  (root; applies at next login)
# ==============================================================================

function Get-PathScopeLabel {
    param([ValidateSet('User', 'System')][string]$Scope = 'User')
    return $Scope
}

# The PowerFlow-managed PATH fragment for a scope.
function Get-PathFragmentPath {
    param([ValidateSet('User', 'System')][string]$Scope = 'User')

    if ($Scope -eq 'System') { return '/etc/profile.d/powerflow-path.sh' }
    return (Join-Path (Get-PowerFlowConfigPath) 'path.ps1')
}

# Directories PowerFlow has persisted for this scope.
function Get-PersistentPathEntries {
    param([ValidateSet('User', 'System')][string]$Scope = 'User')

    $file = Get-PathFragmentPath -Scope $Scope
    if (-not (Test-Path $file)) { return @() }

    # Both fragment formats carry one directory per managed line.
    return @(
        Get-Content $file |
            Where-Object { $_ -match "PF_PATH_ENTRY:(.+)$" } |
            ForEach-Object { $matches[1].Trim() }
    )
}

# Returned as a ':'-delimited string to mirror the Windows adapter's contract.
function Get-PersistentPath {
    param([ValidateSet('User', 'System')][string]$Scope = 'User')
    return ((Get-PersistentPathEntries -Scope $Scope) -join ':')
}

function Test-PersistentPathEntry {
    param(
        [Parameter(Mandatory)][string]$Directory,
        [ValidateSet('User', 'System')][string]$Scope = 'User'
    )

    $normalized = $Directory.TrimEnd('/')
    return ((Get-PersistentPathEntries -Scope $Scope | ForEach-Object { $_.TrimEnd('/') }) -contains $normalized)
}

function Add-PersistentPathEntry {
    param(
        [Parameter(Mandatory)][string]$Directory,
        [ValidateSet('User', 'System')][string]$Scope = 'User'
    )

    if ($Scope -eq 'System' -and -not (Assert-Admin 'System PATH')) { return $false }

    if (Test-PersistentPathEntry -Directory $Directory -Scope $Scope) {
        return $true   # already present — caller reports "nothing to do"
    }

    $file = Get-PathFragmentPath -Scope $Scope

    if ($Scope -eq 'System') {
        # POSIX fragment — applies to login shells at next sign-in.
        $line = "export PATH=`"`$PATH:$Directory`"  # PF_PATH_ENTRY:$Directory"
        $sudo = if (Test-Admin) { '' } else { 'sudo ' }
        bash -c "$sudo touch '$file' && echo '$line' | $sudo tee -a '$file' > /dev/null" 2>&1 | Out-Null
        if ($LASTEXITCODE -ne 0) { return $false }
    }
    else {
        $dir = Split-Path -Parent $file
        if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
        if (-not (Test-Path $file)) {
            Set-Content -Path $file -Value @(
                '# PowerFlow-managed PATH entries. Safe to delete; regenerated by set-path.',
                '# Each managed line ends with a PF_PATH_ENTRY marker — do not remove it.'
            )
        }
        Add-Content -Path $file -Value "`$env:PATH += ':$Directory'  # PF_PATH_ENTRY:$Directory"
    }

    $env:PATH += ":$Directory"
    return (Test-PersistentPathEntry -Directory $Directory -Scope $Scope)
}
